package com.saas.platform.user.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "processed_events", 
       uniqueConstraints = {
           // CRITICAL: The combination of these three must be unique
           @UniqueConstraint(columnNames = {"correlation_id", "tenant_id", "consumer_group"})
       })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProcessedEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The unique ID generated by the Outbox (from the Kafka header)
    @Column(name = "correlation_id", nullable = false, length = 36)
    private String correlationId;

    // The tenant that processed this event (for multi-tenancy)
    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;
    
    // The consumer group ID (or a logical name like "BALANCE_DEDUCTION")
    @Column(name = "consumer_group", nullable = false, length = 100)
    private String consumerGroup; 

    @Column(name = "processed_at", nullable = false)
    private LocalDateTime processedAt;

    // Optional: Event Type, useful for tracking/debugging
    @Column(name = "event_type", length = 100)
    private String eventType;
}